"""initial tables creation

Revision ID: 976a46a02071
Revises: 
Create Date: 2024-11-30 01:15:57.651771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976a46a02071'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('seniority', sa.Text(), nullable=False),
    sa.Column('english_level', sa.Text(), nullable=False),
    sa.Column('tech_stacks', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('primary_tech_stack', sa.Text(), nullable=False),
    sa.Column('hours_per_week', sa.Integer(), nullable=False),
    sa.Column('team_lead', sa.Boolean(), nullable=True),
    sa.Column('flexible_schedule', sa.Boolean(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('histories')
    op.drop_table('users')
    # ### end Alembic commands ###
