"""remove unnecessary column

Revision ID: ca4c39594fff
Revises: c2b289e5ef4c
Create Date: 2024-11-30 04:26:48.314417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca4c39594fff'
down_revision = 'c2b289e5ef4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('histories', schema=None) as batch_op:
        batch_op.drop_column('result')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
